Repository natycavaillier/diario-viagens, pull requests merged in 2022-06, with the labels that each got.

#37 Mensagem Boas Vindas e Despedida
  src/app/auth/auth.module.ts
  src/app/auth/components/login/login.component.ts
  src/app/auth/components/mensagem-saida/mensagem-saida.component.html
  src/app/auth/components/mensagem-saida/mensagem-saida.component.scss
  src/app/auth/components/mensagem-saida/mensagem-saida.component.spec.ts
  src/app/auth/components/mensagem-saida/mensagem-saida.component.ts
  src/app/auth/components/mensagem/mensagem.component.html
  src/app/auth/components/mensagem/mensagem.component.scss
  src/app/auth/components/mensagem/mensagem.component.spec.ts
  src/app/auth/components/mensagem/mensagem.component.ts
  src/app/core/components/navbar/navbar.component.ts
Labels: documentation, enhancement

#38 Estilização Pagina Login
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
Labels: documentation, enhancement

#40 Carrossel
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/components/navbar/navbar.component.scss
  src/app/core/models/diario.ts
  src/app/core/services/diarios/diarios.service.ts
  src/app/dashboard/dashboard.component.html
  src/app/diarios/components/diario-add/diario-add.component.html
  src/app/diarios/components/diario-add/diario-add.component.ts
  src/app/diarios/components/diario-detail/diario-detail.component.html
  src/app/diarios/components/diario-detail/diario-detail.component.scss
  src/app/diarios/components/diario-detail/diario-detail.component.ts
  src/app/diarios/components/diario-edit/diario-edit.component.html
  src/app/diarios/components/diario-edit/diario-edit.component.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.ts
  src/app/diarios/diarios.module.ts
  src/polyfills.ts
  src/styles.scss
Labels: documentation

#41 Aprimoramento do carrossel no diario-list
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.scss
  src/app/core/components/navbar/navbar.component.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
Labels: enhancement

#42 Estilização pages Recuperar Senha e Verificação Usuário
  src/app/auth/components/confere-senha/confere-senha.component.html
  src/app/auth/components/recuperar-senha/recuperar-senha.component.html
  src/app/auth/components/recuperar-senha/recuperar-senha.component.scss
  src/app/auth/components/usuario-nao-verificado/usuario-nao-verificado.component.html
  src/app/auth/components/usuario-nao-verificado/usuario-nao-verificado.component.scss
Labels: documentation, enhancement

#45 Alteração Icone Upload
  package-lock.json
  src/app/diarios/components/diario-add/diario-add.component.html
  src/app/diarios/components/diario-add/diario-add.component.ts
Labels: documentation, enhancement

#50 Ajustes finais
  src/app/app.module.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/politica/politica.component.html
  src/app/diarios/components/politica/politica.component.scss
  src/app/diarios/components/politica/politica.component.spec.ts
  src/app/diarios/components/politica/politica.component.ts
  src/app/diarios/diarios-routing.module.ts
  src/app/diarios/diarios.module.ts
  src/app/home/home-routing.module.ts
  src/app/home/home.module.ts
  src/assets/img/capa.jpg
Labels: enhancement

#51 Atualização Identidade Visual
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.scss
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/styles.scss
Labels: documentation, enhancement
